import Navbar from "./_components/navbar/Navbar"
import Searchbar from "./_components/searchbar/Searchbar"
import "./globals.css";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        <Searchbar/>
        {children}
        </body>
    </html>
  )
}
